---
resources:
- name: pcfapp
  type: git
  source:
    uri: https://github.com/shinyay/pcf-workshop-spring-test.git
    branch: master
  check_every: 10s
- name: deploy-to-cf
  type: cf
  source:
    api: api.run.pcfone.io
    username: ((user-id))
    password: ((user-password))
    organization: pivot-syanagihara
    space: development
    skip_cert_check: true
jobs:
- name: unit-test
  plan:
  - get: pcfapp
    trigger: true
  - task: gradle-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          {repository: java, tag: openjdk-8}
      inputs:
      - name: pcfapp
      run:
        path: bash
        args:
        - -c
        - |
          cd pcfapp
          ./gradlew test
- name: build-and-deploy
  plan:
  - get: pcfapp
    passed: [ unit-test ]
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          {repository: java, tag: openjdk-8}
      inputs:
      - name: pcfapp
      outputs:
      - name: out
      run:
        path: bash
        args:
        - -c
        - |
          cd pcfapp
          ./gradlew clean build -x test
          mv build/libs/testing-0.0.1-SNAPSHOT.jar ../out
  - put: deploy-to-cf
    params:
      manifest: pcfapp/manifest.yml
      current_app_name: hello-pcf-shinyay
      path: out/testing-0.0.1-SNAPSHOT.jar
